fix for CMP

diff --git a/trunk/build_firmware_modify b/trunk/build_firmware_modify
--- a/trunk/build_firmware_modify
+++ b/trunk/build_firmware_modify
@@ -1,13 +1,11 @@
 #!/bin/bash
 
 if [ -z "$1" ] || [ "$EUID" != 0 ]; then
-	echo "Please run 'fakeroot $0 PRODUCT_NAME' to start build (see 'configs/templates/')"
-	echo "For Windows Subsystem for Linux(WSL), use 'fakeroot-tcp' instead of 'fakeroot', or run with sudo"
-	exit 1
+	echo "Please run 'fakeroot $0 PRODUCT_NAME' to start build (see 'configs/templates/') " && exit 1
 fi
-
+if [ -z "$2" ];then
 if [ ! -f configs/templates/$1.config ] ; then
-	echo "configs/templates/$1.config not found!"
+	echo "configs/templates/$1.config not found "
 	exit 1
 fi
 
@@ -53,6 +51,7 @@ echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
 echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #aliddns
 ##内网穿透服务##
 
+fi
 sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
 
 ROOTDIR=`pwd`
